version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-3.4
      - test-2.7
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "dev-requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            rm -rf ./venv
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest -s tests.py
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6.8-stretch
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5.7-stretch
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4.9-stretch
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7.16-stretch
